//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string LEFT_100 = "left_100";
        
        public const string CENTRE_100 = "centre_100";
        
        public const string RIGHT_100 = "right_100";
        
        public const string RIGHT_BACK_100 = "right_back_100";
        
        public const string LEFT_BACK_100 = "left_back_100";
        
        public const string CENTRE_LEFTBACK_100 = "centre_leftback_100";
        
        public const string CENTRE_RIGHTBACK_100 = "centre_rightback_100";
    }
}
